module.exports = {
  usersPerPage: 100,
  clientId: 'gp762nuuoqcoxypju8c569th9wz7q5',
  oauth: '0ekw7q9n0rwxnzcr13hp2lkc9cdklq',

  chatbot: {
    sleepAfterConnect: 1000,
    bearer: `Bearer ${require('../../knex/seeds').users[0].jwtoken}`,

    endpoint: '/twitch',
    channel: 'teazyou',

    tmiOpts: {
      options: { debug: false },
      connection: {
        reconnect: true,
        secure: true,
      },
      identity: {
        username: 'TeazWar',
        // oauth generated by https://twitchapps.com/tmi/
        password: 'oauth:00cgu2v9hgxeachs4no1lxpbvezzit',
      },
      // channels: ['TeazYou'],
    },
  },
}
